#!/bin/bash
# Runs once, only when /data/db is empty (fresh volume). Creates two users on
# top of the root user the image already made:
#
#   app  - readWrite on the application database only. This is what the
#          service connects as.
#   ops  - backup + restore roles on admin. Used by scripts/backup.sh and
#          scripts/restore.sh so day-to-day tooling never needs root.
#
# Passwords come from docker secrets, never from the environment.
set -euo pipefail

app_pw="$(cat /run/secrets/mongo_app_password)"
ops_pw="$(cat /run/secrets/mongo_ops_password)"
db="${MONGO_DB:-gsp}"

# Credentials go in via stdin rather than argv so they don't show up in ps.
# Passwords are generated by scripts/init-secrets.sh as hex, so no quoting issues.
mongosh --quiet admin <<JS
db.auth('${MONGO_INITDB_ROOT_USERNAME}', '${MONGO_INITDB_ROOT_PASSWORD}');
db.getSiblingDB('${db}').createUser({
  user: 'app',
  pwd: '${app_pw}',
  roles: [{ role: 'readWrite', db: '${db}' }],
});
db.createUser({
  user: 'ops',
  pwd: '${ops_pw}',
  roles: [{ role: 'backup', db: 'admin' }, { role: 'restore', db: 'admin' }],
});
JS

echo "created users app (readWrite on ${db}) and ops (backup/restore)"
